### ISSUE TITLE
Replacing the old hyperjaxb3 plugin

### ISSUE THREAD

**Issue by taijidude** [patrodyne/hisrc-hyperjaxb#3]
Hello, 

i'm responsible the update an application which uses the maven-hyperjaxb3-plugin. Is it possible to migrate to your fork? And if yes, what would the steps be?

**Comment by patrodyne** [comment]
Yes, you can replace the old `maven-hyperjaxb3-plugin` with the new `hisrc-hyperjaxb-maven-plugin`. To get started, download [hisrc-hyperjaxb-ejb-sample-po-initial-2.2.0-mvn-src.zip](https://github.com/patrodyne/hisrc-hyperjaxb/releases/download/2.2.0/hisrc-hyperjaxb-ejb-sample-po-initial-2.2.0-mvn-src.zip) and unzip it locally. The zip is a _stand-alone_ Maven project to demonstrate the `hisrc-hyperjaxb-maven-plugin`. 

From the command line, change to your local folder where you unzipped the sample and run the test and/or sample application using either of two included JPA providers:

[Eclipselink](https://www.eclipse.org/eclipselink/)
~~~
mvn -Peclipselink clean test
mvn -Peclipselink clean compile exec:java
~~~

[Hibernate](https://hibernate.org/orm/)
~~~
mvn -Phibernate clean test
mvn -Phibernate clean compile exec:java
~~~

You can review the configuration options using:

**HyperJAXB Help**
~~~
mvn hisrc-hyperjaxb:help -Ddetail=true
~~~

The [HiSrc HyperJAXB Sample PO-Initial](https://github.com/patrodyne/hisrc-hyperjaxb/blob/master/ejb/assembly/samples/po-initial/README.md) project uses the `hisrc-hyperjaxb-maven-plugin` to read the XML Schema and JAXB Binding files from the `src/main/resources/` sub-directory and generate JAXB/JPA classes in the `target/generated-sources/xjc/` path. When either the test or sample application is executed, the JPA configuration creates an H2 database at `target/test-database/` then unmarshalls the sample XML files from `src/test/samples/` into JAXB objects. Additionally, the objects have JPA annotations and can be used as JPA entities. The test and sample application persist the entities to the test database then reverses the process to output the XML samples to the console.

> **Note:** The test and/or sample application generates the SQL DDL used to create the tables at `target/test-database-sql`.

You can compare the sample POM to your existing POM and experiment with the `hisrc-hyperjaxb-maven-plugin`. See also the **HyperJAXB** package and name changes in the [Version 2.0.0](https://github.com/patrodyne/hisrc-hyperjaxb#version-200) section of the **HyperJAXB** project page.

**Explore More**

For a deeper exploration you can download [hisrc-hyperjaxb-ex001-2.2.0-mvn-src.zip](https://github.com/patrodyne/hisrc-hyperjaxb/releases/download/2.2.0/hisrc-hyperjaxb-ex001-2.2.0-mvn-src.zip) to another local folder and start an interactive GUI demo using `explore.sh` or `explore.cmd`. Here is the non-interactive [README](https://github.com/patrodyne/hisrc-hyperjaxb/blob/master/ejb/assembly/explore/Ex001-JustProduct/src/test/resources/org/patrodyne/jvnet/hyperjaxb/ex001/Explorer.md).

**Comment by taijidude** [comment]
Thank you a lot. This helped a ton. Now i get an exception which i says i use the unsupported Namespace: org.xml.sax.SAXParseException: unsupported Binding Namespace "http://jvnet.org/basicjaxb/xjc/annox/org.hibernate.annotations".

The part in the xsd where it is used looks like this: 

```xsd 
<xs:element name="nachricht" type="xs:base64Binary" minOccurs="0">
  <xs:annotation>
    <xs:appinfo>
      <annox:annotate>
        <ha:Type type="org.hibernate.type.BinaryType" />
      </annox:annotate>
    </xs:appinfo>
  </xs:annotation>
</xs:element>
```

**Comment by patrodyne** [comment]
To recreate the exception, I modified [hisrc-hyperjaxb-ejb-sample-po-initial-2.2.0-mvn-src.zip](https://github.com/patrodyne/hisrc-hyperjaxb/releases/download/2.2.0/hisrc-hyperjaxb-ejb-sample-po-initial-2.2.0-mvn-src.zip), as follows:

Declare additional namespaces for `annox`, `ha` and `jaxb` to `src/main/resources/PurchaseOrder.xsd`.
~~~
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://example.org/po"
    targetNamespace="http://example.org/po"
    elementFormDefault="qualified"
    xmlns:annox="http://jvnet.org/basicjaxb/xjc/annox" 
    xmlns:ha="http://jvnet.org/basicjaxb/xjc/annox/org.hibernate.annotations"
    xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
    jaxb:extensionBindingPrefixes="annox ha"
>
~~~

Added the `nachricht` as a sub-element of the `PurchaseOrder` element.
~~~
<xsd:element name="purchaseOrder">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="shipTo" type="tns:USAddress"/>
      <xsd:element name="billTo" type="tns:USAddress"/>
      <xsd:element ref="tns:comment" minOccurs="0"/>
      <xsd:element name="items"  type="tns:Items"/>

      <xsd:element name="nachricht" type="xsd:base64Binary" minOccurs="0">
        <xsd:annotation>
          <xsd:appinfo>
            <annox:annotate>
              <ha:Type type="org.hibernate.type.BinaryType" />
              <!-- <ha:Type value="org.hibernate.usertype.UserTypeLegacyBridge" /> -->
            </annox:annotate>
          </xsd:appinfo>
        </xsd:annotation>
      </xsd:element>

    </xsd:sequence>
    <xsd:attribute name="orderDate" type="xsd:dateTime"/>
  </xsd:complexType>
</xsd:element>

~~~

**Build:** `mvn -Phibernate clean test`

**Issue 1**

Adding `ha` to the list of XJC extension binding prefixes is incorrect. It is not a XJC plugin; instead, it is de-referenced in the `annox` plugin. This causes `org.xml.sax.SAXParseException: Unsupported binding namespace`. _The fix_ is to remove `ha` from `jaxb:extensionBindingPrefixes="annox ha"` to be just `jaxb:extensionBindingPrefixes="annox"`.

**Build:** `mvn -Phibernate clean test`

**Issue 2**

Hibernate 6.x changed its `Type` annotation to a new package and with new behavior.

~~~
org.xml.sax.SAXParseException: Cannot annotate com.sun.codemodel.JMethod@795b66d

Caused by: org.jvnet.basicjaxb_annox.parser.exception.AnnotationElementParseException:
    Could not parse the annotation element.

Caused by: org.jvnet.basicjaxb_annox.annotation.AnnotationClassNotFoundException:
    Annotation class [org.hibernate.annotations.Type] could not be found.

Caused by: java.lang.ClassNotFoundException:
    org.hibernate.annotations.Type
~~~

_The fix_ is to, first, change the Hibernate `Type` in the `nachricht` element and, second, to configure the `hisrc-hyperjaxb-maven-plugin` to depend on the `hibernate-core` library so it can resolve the type. 

~~~
<!-- <ha:Type type="org.hibernate.type.BinaryType" /> -->
<ha:Type value="org.hibernate.usertype.UserTypeLegacyBridge" />
~~~

Reconfigure `hisrc-hyperjaxb-maven-plugin` to use Hibernate types too.

**pom.xml**
~~~
...
<plugin>
    <groupId>org.patrodyne.jvnet</groupId>
    <artifactId>hisrc-hyperjaxb-maven-plugin</artifactId>
    <version>${hisrc-hyperjaxb.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate-series.version}</version>
        </dependency>
    </dependencies>
    <executions>
    ...
    </executions>
</plugin>
...
~~~

**Build:** `mvn -Phibernate clean test`

**Issue 3**

The build generates The Hibernate 6.x annotation but the XSD did not provide parameters ...

`target/generated-sources/xjc/org/example/po/PurchaseOrder.java`
~~~
...
@Type(value = UserTypeLegacyBridge.class, parameters = { })
@Basic
@Column(name = "NACHRICHT")
@Lob
public byte[] getNachricht()
{
    return nachricht;
}
...
~~~

... which causes a the unit test to fail ...

~~~
[ERROR] org.example.po.RoundtripTest.testSamples -- Time elapsed: 1.317 s <<< ERROR!
org.hibernate.MappingException: Missing `@Parameter` for `hbm-type-name`
~~~

_The fix_ is to ask, "What parameters does Hibernate 6.x need to mimic the 5.x `org.hibernate.type.BinaryType`?"

The answer may be [using-type-for-binary-data-in-hibernate-6](https://stackoverflow.com/questions/75354646/), use only JPA annotations.

**Comment by patrodyne** [comment]
Remaining issue is a Hibernate issue.

**Comment by taijidude** [comment]
Thank you. Got it running.
